set dotenv-load


build:
  rm -rf dist
  mkdir -p dist
  cp -R ./static/ ./dist/
  pkgx npx tailwindcss -- --config=tailwind.config.js --input=./css/main.css --output=./dist/stylesheet.css --minify
  cd build && gren make Build.gren
  cd build && pkgx node app
  rm build/app
  cd dynamic && gren make Main.gren --output=../dist/site.js --optimize

publish: build
  #!/usr/bin/env bash
  cid=$(pkgx npx w3 -- up ./dist/ | tail -n 1 | sed "s/⁂ https:\/\/w3s.link\/ipfs\///")
  # https://dns-lexicon.readthedocs.io/
  echo "Publishing $cid"
  lexicon dnsimple --auth-token $DNS_AUTH_TOKEN --content $cid update _dnslink.tokono.ma TXT
